export {
  AI_PROVIDERS,
  AI_PROVIDER_DEFAULT_BASE_URL,
  AI_PROVIDER_MODELS,
  DEFAULT_AI_PROVIDER,
  DEFAULT_AI_MODEL,
  DEFAULT_AI_RUNTIME_PORT,
  MIN_AI_RUNTIME_PORT,
  MAX_AI_RUNTIME_PORT,
  aiProviderNeedsApiKey,
  aiProviderUsesOpenAiApi,
  isAiPresetModel,
  isAiApiKeyConfigured,
  isAiRuntimeConfigured,
  normalizeAiProvider,
  normalizeAiModel,
  normalizeAiBaseUrl,
  normalizeAiRuntimePort,
  type AiProvider,
} from '../../electron/shared/ai-provider-settings'
